### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by dvir-biton**

### CODE REVIEW

**Comment by HannesWell** [comment]
Thanks for this fix.

Unfortunately I have to check first if we need you to sign the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/eca/faq/) or not: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/5288

I understand that this is a lot of overhead for just a trivial typo fix and I hope that it's not required, but since this repo is quite new we have to check this first. Sorry for the inconvenience and I'll call you back.

**Comment by dvir-biton** [comment]
Hi, I signed it now. I plan to contribute more in the future, so I had to do it anyway. Thank you.

**Comment by HannesWell** [comment]
> Hi, I signed it now. 

Great. Thanks! I just squashed the two commits into one.

> I plan to contribute more in the future, so I had to do it anyway. Thank you.

Great, do you already have plans where or what exactly?

**Comment by dvir-biton** [comment]
Thank you! I plan to focus on improving areas where I can contribute the most such as UI enhancements and bug fixes.

**Comment by HannesWell** [comment]
Sounds good :)
In that case you might be interested in the [eclipse.platform.ui](https://github.com/eclipse-platform/eclipse.platform.ui).

**Pull request merged**
